blank_issues_enabled: false
contact_links:
  - name: Support and Knowledge Base
    url: https://rancherfederal.zendesk.com/
    about: For support with Carbide software please visit our official support site.
